require("prototypes.entity")
require("prototypes.font")
require("prototypes.item")
require("prototypes.recipe")
require("prototypes.signals")
require("prototypes.style")
require("prototypes.technology")
